# Generated by Django 5.0.7 on 2024-07-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookapoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('symptoms', models.CharField(max_length=250)),
                ('choose_date_1', models.DateField()),
            ],
        ),
    ]
