# Generated by Django 5.0.7 on 2024-07-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('patient_disease', models.TextField()),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('C', 'Completed'), ('P', 'Pending')], max_length=1)),
            ],
        ),
    ]
